import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import TopBanner from "@/components/layout/Banner/TopBanner";
import TopNavbar from "@/components/layout/Navbar/TopNavbar";
import Footer from "@/components/layout/Footer";
import HolyLoaderSimple from "@/components/ui/HolyLoaderSimple";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Shopco",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/_next/static/css/29847d2730b36d6c.css"
          as="style"
        />
        <link
          rel="stylesheet"
          href="/_next/static/css/29847d2730b36d6c.css"
          media="print"
          onLoad={(e) => ((e.currentTarget as HTMLLinkElement).media = "all")}
        />
        <link
          rel="preload"
          href="/_next/static/css/3b60e469efec1c46.css"
          as="style"
        />
        <link
          rel="stylesheet"
          href="/_next/static/css/3b60e469efec1c46.css"
          media="print"
          onLoad={(e) => ((e.currentTarget as HTMLLinkElement).media = "all")}
        />
      </head>
      <body className={satoshi.className}>
        <HolyLoaderSimple color="#868686" />
        <TopBanner />
        <Providers>
          <TopNavbar />
          {children}
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
